### ISSUE TITLE
図を保存する関数について

### ISSUE THREAD

**Issue by syunna5** [superkerokero/naruhodo#14]
plotToFileによって図を保存できますが、同時に画面にも出力されるようです。
この場合、グラフィカル環境のないサーバー上ではエラーが出てしまいます。
図を保存するのみの関数はないのでしょうか？

**Comment by superkerokero** [comment]
Pull request #15 でこの問題を解決しました。そちらのコードを使えばファイル出力のみになります。

**Comment by syunna5** [comment]
ありがとうございます！助かりました。
